# Generated by Django 3.2.3 on 2021-06-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadress',
            old_name='adress',
            new_name='address',
        ),
    ]
